"""The shared corpus: configuration documents both validators must classify identically.

``export-pipeline-spec.md`` asks for this rather than for a generated-and-diffed comparison of
the JSON Schema against the Pydantic models. Diffing the two would test the *representation*, and
the two legitimately differ in spelling -- ``unevaluatedProperties`` against
``additionalProperties``, ``if``/``then`` against a ``model_validator``. What must agree is the
**verdict**, so the corpus is a set of documents each marked valid or invalid with the reason, and
the rule is that both sides say the same thing about every one.

Each case is a mutation of one valid base document, so a case describes exactly one difference and
a failure names it. ``structurally_valid`` is what the schema and the models must agree on;
semantic-only rules are marked ``structurally_valid=True`` with ``semantic=True``, because those
are deliberately outside the schema's reach and are checked against
:func:`pqx_plan.semantics.findings` instead.

**Why this ships in the package rather than living beside the tests.** ``export-pipeline-spec.md``
says the corpus doubles as the fixture set for the web configuration editor, which is a separate
tool in a different language. Keeping it importable means the exported
``docs/export-config-corpus.json`` can be regenerated by anyone who has this package, rather than
only from inside this repository's test session.
"""

from __future__ import annotations

import copy
import json
from dataclasses import dataclass
from typing import Any

BASE: dict[str, Any] = {
    "config_version": 1,
    "config_id": "0f7c1a94-3b52-4c8e-9a1d-6e2f0b5d7c33",
    "config_modified_utc": "2026-09-13T16:04:11Z",
    "output_directory": "az://exports/monthly",
    "sidecar_location": {"kind": "beside_source"},
    "scratch_root": None,
    "excel": {"writer": "rustpy-xlsxwriter", "options": {}},
    "sources": {
        "sales": {"path": "../data/sales.parquet", "date_columns": {"transaction_date": {"type": "date"}}},
        "returns": {"path": "../data/returns.parquet", "date_columns": {"returned_on": {"type": "int", "format": "YYYYMMDD"}}},
    },
    "profiles": [
        {
            "name": "annual_review",
            "output_subdirectory": "annual_review",
            "limits": {"max_data_rows_per_worksheet": 1048575, "max_cells_per_workbook": 10000000},
            "partitioning": {
                "algorithm": "calendar_greedy",
                "base_period": "year",
                "period_order": "ascending",
                "year_split_months": [6, 4, 3, 2, 1],
                "oversized_period": "balanced_rows",
                "null_dates": "separate",
            },
            "naming": {
                "workbook": "{profile}_{period_label}_{workbook_index:03d}.xlsx",
                "worksheet": "{source} {period_label}",
                "single_worksheet": "{source} Data",
                "overflow_worksheet": "{source} {period_label}_p{part_index:02d}",
                "month_format": "numeric",
                "worksheet_prefix": "",
                "sheet_collision": "error",
            },
            "sheets": [
                {"source": "sales", "partition_column": "transaction_date", "sort": [{"column": "customer_id", "direction": "ascending", "nulls": "last"}]},
                {"source": "returns", "partition_column": "returned_on", "sort": []},
            ],
        },
    ],
}
"""A valid configuration exercising fan-in, a calendar grid, and both date-column kinds."""


@dataclass(frozen=True, slots=True)
class Case:
    """One corpus entry: a document, the verdict both sides must reach, and why.

    Attributes:
        identifier: Stable name, used in test ids and in the exported artifact.
        reason: What this case is about, in one line.
        structurally_valid: What the schema and the models must both say.
        document: The whole configuration document.
        semantic: Whether this case is structurally fine and semantically wrong. Such a case is
            invisible to the schema by design, so it is checked against the semantic validator
            rather than counted as a divergence.
        findings: How many semantic findings a ``semantic`` case must produce.
        dialect_divergence: Whether Python's ``jsonschema`` reads the schema's own regular
            expression differently from ECMA-262, which is what JSON Schema specifies and what a
            browser-based editor uses. Recorded rather than hidden: these cases are exempt from
            the agreement assertion and get their own test, which pins down exactly which side
            says what. ``structurally_valid`` states the **intended** (ECMA-262) verdict.
    """

    identifier: str
    reason: str
    structurally_valid: bool
    document: dict[str, Any]
    semantic: bool = False
    findings: int = 0
    dialect_divergence: bool = False


def _mutate(**top_level: object) -> dict[str, Any]:
    """Return the base document with top-level keys replaced."""
    document: dict[str, Any] = copy.deepcopy(BASE)
    document.update(top_level)
    return document


def _profile(**changes: object) -> dict[str, Any]:
    """Return the base document with the single profile's keys replaced."""
    document: dict[str, Any] = copy.deepcopy(BASE)
    document["profiles"][0].update(changes)
    return document


def _partitioning(**changes: object) -> dict[str, Any]:
    """Return the base document with the profile's partitioning keys replaced."""
    document: dict[str, Any] = copy.deepcopy(BASE)
    document["profiles"][0]["partitioning"].update(changes)
    return document


def _naming(**changes: object) -> dict[str, Any]:
    """Return the base document with the profile's naming keys replaced."""
    document: dict[str, Any] = copy.deepcopy(BASE)
    document["profiles"][0]["naming"].update(changes)
    return document


def _limits(**changes: object) -> dict[str, Any]:
    """Return the base document with the profile's limits replaced."""
    document: dict[str, Any] = copy.deepcopy(BASE)
    document["profiles"][0]["limits"].update(changes)
    return document


def _sort(column: str, direction: str = "ascending", nulls: str = "last") -> dict[str, Any]:
    """Return one sort key.

    A constructor rather than a literal at each call site, so the resulting document carries a
    known element type. A bare ``[]`` inside a nested literal infers as ``list[Unknown]``, which
    strict type checking reports for every case that holds one.
    """
    return {"column": column, "direction": direction, "nulls": nulls}


def _sheet(source: str, partition_column: str | None, sort: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    """Return one sheet entry, with an empty sort by default."""
    keys: list[dict[str, Any]] = [] if sort is None else sort
    return {"source": source, "partition_column": partition_column, "sort": keys}


def _sheets(*entries: dict[str, Any]) -> list[dict[str, Any]]:
    """Return a typed list of sheet entries."""
    return list(entries)


def _date_column(column: dict[str, Any], *, alias: str = "sales", name: str = "transaction_date") -> dict[str, Any]:
    """Return the base document with one source's single date column replaced."""
    document: dict[str, Any] = copy.deepcopy(BASE)
    document["sources"][alias]["date_columns"] = {name: column}
    document["profiles"][0]["sheets"][0]["partition_column"] = name
    return document


def _balanced() -> dict[str, Any]:
    """Return the base document switched to balanced partitioning, with null partition columns."""
    document: dict[str, Any] = copy.deepcopy(BASE)
    document["profiles"][0]["partitioning"] = {"algorithm": "balanced", "balance_across": "worksheets"}
    sheet: dict[str, Any]
    for sheet in document["profiles"][0]["sheets"]:
        sheet["partition_column"] = None
    return document


def _drop(path: tuple[str | int, ...]) -> dict[str, Any]:
    """Return the base document with one key removed, addressed by a path of keys and indices."""
    document: dict[str, Any] = copy.deepcopy(BASE)
    cursor: Any = document
    step: str | int
    for step in path[:-1]:
        cursor = cursor[step]
    del cursor[path[-1]]
    return document


VALID: list[Case] = [
    Case("base", "the shipped example shape: fan-in, a calendar grid, both date-column kinds", True, copy.deepcopy(BASE)),
    Case("schema_pointer", "an editor's $schema pointer at the top of the document", True, _mutate(**{"$schema": "./export-config.schema.json"})),
    Case("balanced_null_partition_column", "balanced consults no date, so every partition_column is null", True, _balanced()),
    Case("balanced_across_workbooks", "the other balanced mode", True, {**_balanced(), "profiles": [{**_balanced()["profiles"][0], "partitioning": {"algorithm": "balanced", "balance_across": "workbooks"}}]}),
    Case("directory_sidecar", "sidecars gathered under one directory instead of beside each source", True, _mutate(sidecar_location={"kind": "directory", "path": "../sidecars"})),
    Case("scratch_root_set", "an explicit scratch root rather than the platform temporary directory", True, _mutate(scratch_root="/mnt/fast/scratch")),
    Case("abbreviated_months", "abbreviated month labels", True, _naming(month_format="abbreviated")),
    Case("sheet_collision_suffix", "the suffixing collision policy", True, _naming(sheet_collision="suffix")),
    Case("worksheet_prefix", "a literal prefix on every rendered worksheet name", True, _naming(worksheet_prefix="debits")),
    Case("calendar_periods", "one base period per sheet rather than greedy merging", True, _partitioning(algorithm="calendar_periods")),
    Case("descending_periods", "newest first", True, _partitioning(period_order="descending")),
    Case("month_base_period", "a monthly grid", True, _partitioning(base_period="year-month")),
    Case("partial_year_split_grids", "a profile may omit unwanted intermediate grids", True, _partitioning(year_split_months=[6, 3, 1])),
    Case("oversized_period_error", "refuse an oversized bucket rather than splitting it by rows", True, _partitioning(oversized_period="error")),
    Case("null_dates_error", "refuse null dates rather than bucketing them as Undated", True, _partitioning(null_dates="error")),
    Case("int_yymm_with_window", "a two-digit year format with its required window", True, _date_column({"type": "int", "format": "YYMM", "two_digit_year_window_start": 1970})),
    Case("int_yymmdd_with_window", "the other two-digit format", True, _date_column({"type": "int", "format": "YYMMDD", "two_digit_year_window_start": 1970})),
    Case("int_yyyymm", "a four-digit month format with no window", True, _date_column({"type": "int", "format": "YYYYMM"})),
    Case("datetime_wall_clock", "a datetime read in the source's own wall clock", True, _date_column({"type": "datetime", "calendar_timezone": {"mode": "source_wall_clock"}})),
    Case("datetime_named_zone", "a datetime converted to a named IANA zone first", True, _date_column({"type": "datetime", "calendar_timezone": {"mode": "zone", "zone": "America/Mexico_City"}})),
    Case("offset_timestamp", "config_modified_utc written with an offset rather than Z", True, _mutate(config_modified_utc="2026-09-13T10:04:11-06:00")),
    Case(
        "empty_date_columns",
        "a source registering nothing, legitimate under balanced",
        True,
        {**_balanced(), "sources": {**copy.deepcopy(BASE["sources"]), "sales": {"path": "../data/sales.parquet", "date_columns": {}}}},
    ),
    Case(
        "several_sort_keys",
        "a lexicographic sort over three columns",
        True,
        _profile(
            sheets=[
                {
                    "source": "sales",
                    "partition_column": "transaction_date",
                    "sort": [{"column": "a", "direction": "ascending", "nulls": "last"}, {"column": "b", "direction": "descending", "nulls": "first"}, {"column": "c", "direction": "ascending", "nulls": "first"}],
                },
                copy.deepcopy(BASE["profiles"][0]["sheets"][1]),
            ]
        ),
    ),
]
"""Documents both sides must accept."""

INVALID: list[Case] = [
    Case("unknown_top_level_key", "an unknown field is rejected, not ignored", False, _mutate(unexpected="value")),
    Case("wrong_config_version", "only version 1 is read", False, _mutate(config_version=2)),
    Case("missing_config_id", "identity is required for output-directory ownership", False, _drop(("config_id",))),
    Case("empty_config_id", "an empty identity identifies nothing", False, _mutate(config_id="")),
    Case("naive_timestamp", "a timestamp with no offset names no instant", False, _mutate(config_modified_utc="2026-09-13T16:04:11")),
    Case("unparseable_timestamp", "not a timestamp at all", False, _mutate(config_modified_utc="last Tuesday")),
    Case("empty_output_directory", "an empty destination addresses nothing", False, _mutate(output_directory="")),
    Case("missing_scratch_root", "null is written down rather than left out", False, _drop(("scratch_root",))),
    Case("empty_scratch_root", "an empty string is not a directory; null means the platform default", False, _mutate(scratch_root="")),
    Case("refused_writer", "polars-xlsxwriter is not round-trip safe, so verification would fail on the writer", False, _mutate(excel={"writer": "polars-xlsxwriter", "options": {}})),
    Case("missing_excel_options", "options is required even when empty", False, _drop(("excel", "options"))),
    Case("sidecar_directory_without_path", "the directory kind needs a directory", False, _mutate(sidecar_location={"kind": "directory"})),
    Case("sidecar_unknown_kind", "an unlisted sidecar location", False, _mutate(sidecar_location={"kind": "wherever"})),
    Case("no_sources", "an export with no sources exports nothing", False, _mutate(sources={})),
    Case("no_profiles", "an export with no profiles produces nothing", False, _mutate(profiles=[])),
    Case("source_alias_with_a_space", "aliases are interpolated into names", False, _mutate(sources={"my sales": copy.deepcopy(BASE["sources"]["sales"])})),
    Case("missing_date_columns", "the key is required even when the mapping is empty", False, _drop(("sources", "sales", "date_columns"))),
    Case("empty_date_column_name", "a date column keyed by nothing names no column", False, _date_column({"type": "date"}, name="")),
    Case("date_column_unknown_type", "floats, booleans and strings are refused as date columns", False, _date_column({"type": "float"})),
    Case("date_column_with_a_format", "format belongs to the int kind; the closed object rejects it here", False, _date_column({"type": "date", "format": "YYMM"})),
    Case("int_without_format", "an integer date is interpreted only under a declared format", False, _date_column({"type": "int"})),
    Case("int_unknown_format", "only the four listed encodings are read", False, _date_column({"type": "int", "format": "YYYYDDMM"})),
    Case("yymm_without_window", "a two-digit year is ambiguous without a fixed window", False, _date_column({"type": "int", "format": "YYMM"})),
    Case("yyyymm_with_window", "a window beside a four-digit year is forbidden, not merely unused", False, _date_column({"type": "int", "format": "YYYYMM", "two_digit_year_window_start": 1970})),
    Case("window_out_of_range", "9901 would put the window's end past year 9999", False, _date_column({"type": "int", "format": "YYMM", "two_digit_year_window_start": 9901})),
    Case("datetime_without_timezone_policy", "which calendar date a timestamp falls on is a choice", False, _date_column({"type": "datetime"})),
    Case("zone_without_a_zone", "the zone mode needs a zone", False, _date_column({"type": "datetime", "calendar_timezone": {"mode": "zone"}})),
    Case("empty_zone", "an empty zone names nothing", False, _date_column({"type": "datetime", "calendar_timezone": {"mode": "zone", "zone": ""}})),
    Case("unknown_timezone_mode", "an unlisted timezone mode", False, _date_column({"type": "datetime", "calendar_timezone": {"mode": "utc"}})),
    Case("profile_name_with_a_dot", "profile names are interpolated into filenames", False, _profile(name="annual.review")),
    Case("empty_output_subdirectory", "a profile owns a directory, so it must name one", False, _profile(output_subdirectory="")),
    Case("no_sheets", "a profile with no sheets produces no worksheets", False, _profile(sheets=[])),
    Case("row_limit_zero", "a worksheet holding no data rows is not a limit, it is a refusal", False, _limits(max_data_rows_per_worksheet=0)),
    Case("row_limit_over_excel", "1,048,576 rows leaves no room for the header", False, _limits(max_data_rows_per_worksheet=1048576)),
    Case("cell_budget_zero", "a budget of zero cells fits no header", False, _limits(max_cells_per_workbook=0)),
    Case("missing_limits", "the ceilings are explicit, never defaulted", False, _drop(("profiles", 0, "limits"))),
    Case("balanced_with_a_calendar_grid", "balanced consults no date, so it declares no grid", False, _partitioning(algorithm="balanced", balance_across="worksheets")),
    Case("calendar_missing_null_dates", "what happens to null dates is stated, never defaulted", False, _drop(("profiles", 0, "partitioning", "null_dates"))),
    Case("unknown_algorithm", "an unlisted partitioning algorithm", False, _partitioning(algorithm="round_robin")),
    Case("year_split_unsupported_grid", "five months leaves a ragged last bucket", False, _partitioning(year_split_months=[5, 1])),
    Case("year_split_duplicate_grid", "a repeated grid would be tried twice", False, _partitioning(year_split_months=[6, 6, 1])),
    Case("year_split_empty", "at least the monthly grid must be available", False, _partitioning(year_split_months=[])),
    Case("unknown_month_format", "an unlisted month format", False, _naming(month_format="abbrev")),
    Case("unknown_sheet_collision", "an unlisted collision policy", False, _naming(sheet_collision="warn")),
    Case("empty_workbook_template", "an empty filename template renders no filename", False, _naming(workbook="")),
    Case("missing_worksheet_prefix", "the prefix is explicit even when empty", False, _drop(("profiles", 0, "naming", "worksheet_prefix"))),
    Case(
        "sort_key_missing_nulls",
        "null placement is stated, never defaulted",
        False,
        _profile(sheets=_sheets({"source": "sales", "partition_column": "transaction_date", "sort": [{"column": "customer_id", "direction": "ascending"}]})),
    ),
    Case("sort_key_unknown_direction", "an unlisted sort direction", False, _profile(sheets=_sheets(_sheet("sales", "transaction_date", [_sort("c", "asc")])))),
    Case("sheet_missing_sort", "an empty array means source order; a missing key means someone forgot", False, _profile(sheets=_sheets({"source": "sales", "partition_column": "transaction_date"}))),
    Case("empty_partition_column", "an empty column name names no column", False, _profile(sheets=_sheets(_sheet("sales", "")))),
]
"""Documents both sides must reject, each for the reason named."""

DIALECT: list[Case] = [
    Case(
        "source_alias_with_a_trailing_newline",
        "ECMA-262 and Pydantic refuse it; Python's jsonschema accepts it, and a newline would reach a worksheet name",
        False,
        _mutate(sources={"sales\n": copy.deepcopy(BASE["sources"]["sales"])}),
        dialect_divergence=True,
    ),
    Case(
        "profile_name_with_a_trailing_newline",
        "the same anchor divergence on a profile name, which reaches a filename",
        False,
        _profile(name="annual_review\n"),
        dialect_divergence=True,
    ),
    Case(
        "sheet_source_with_a_trailing_newline",
        "the same anchor divergence on a sheet's source reference",
        False,
        _profile(sheets=_sheets(_sheet("sales\n", "transaction_date"))),
        dialect_divergence=True,
    ),
]
"""Documents whose verdict depends on which regular-expression dialect reads the schema.

Not a bug in this project's models, which take the strict reading the specification intends. A
wart of the Python ``jsonschema`` library, which implements ``pattern`` with Python's ``re``
where ``$`` also matches before a trailing newline. Recorded so that a reader who finds these
accepted by a Python validator knows it is expected, and that the web editor will not agree.
"""

SEMANTIC: list[Case] = [
    Case("undeclared_source_alias", "a sheet naming a source nothing declares", True, _profile(sheets=_sheets(_sheet("refunds", "x"))), semantic=True, findings=2),
    Case("partition_column_not_registered", "partitioning on a column that source never registered", True, _profile(sheets=_sheets(_sheet("sales", "order_date"))), semantic=True, findings=2),
    Case("partition_column_from_another_source", "a column registered, but in a different source", True, _profile(sheets=_sheets(_sheet("sales", "returned_on"))), semantic=True, findings=2),
    Case("null_partition_column_under_calendar", "a calendar grid with nothing to bucket on", True, _profile(sheets=_sheets(_sheet("sales", None))), semantic=True, findings=2),
    Case(
        "partition_column_under_balanced",
        "balanced consults no date, so a column here means the author expected one",
        True,
        {
            **_balanced(),
            "profiles": [
                {
                    **copy.deepcopy(_balanced()["profiles"][0]),
                    "sheets": _sheets(_sheet("sales", "transaction_date"), _sheet("returns", "returned_on")),
                },
            ],
        },
        semantic=True,
        findings=2,
    ),
    Case(
        "month_precision_under_a_daily_grid",
        "YYYYMM cannot express a day without inventing one",
        True,
        {
            **_date_column({"type": "int", "format": "YYYYMM"}),
            "profiles": [{**copy.deepcopy(BASE["profiles"][0]), "partitioning": {**copy.deepcopy(BASE["profiles"][0]["partitioning"]), "base_period": "year-month-day"}}],
        },
        semantic=True,
        findings=1,
    ),
    Case("worksheet_template_without_source", "two sheets rendering one name", True, _naming(worksheet="{period_label}"), semantic=True, findings=1),
    Case("overflow_template_without_source", "the same rule on the overflow template", True, _naming(overflow_worksheet="{period_label}_p{part_index:02d}"), semantic=True, findings=1),
    Case("unknown_template_token", "a token nothing will substitute", True, _naming(workbook="{profile}_{quarter}.xlsx"), semantic=True, findings=1),
    Case("template_reaching_an_attribute", "str.format_map bounds which names a template reaches, not what it reaches through them", True, _naming(workbook="{profile.__class__}.xlsx"), semantic=True, findings=1),
    Case("template_indexing_a_value", "the same hole, by subscript", True, _naming(worksheet="{source} {period_label[0]}"), semantic=True, findings=1),
    Case("worksheet_token_in_a_workbook_template", "part_index has no meaning in a filename", True, _naming(workbook="{profile}_p{part_index}.xlsx"), semantic=True, findings=1),
    Case("year_split_not_descending", "the grids are tried in order, so the order is the rule", True, _partitioning(year_split_months=[1, 6]), semantic=True, findings=1),
    Case("year_split_not_ending_in_one", "stopping at 3 escalates a large quarter straight to a row split", True, _partitioning(year_split_months=[6, 3]), semantic=True, findings=1),
    Case(
        "duplicate_sort_column",
        "the second key can never change the order",
        True,
        _profile(sheets=_sheets(_sheet("sales", "transaction_date", [_sort("c"), _sort("c", "descending", "first")]))),
        semantic=True,
        findings=2,
    ),
    Case("unread_source", "a renamed alias in sheets that was not renamed in sources", True, _profile(sheets=_sheets(_sheet("sales", "transaction_date"))), semantic=True, findings=1),
    Case("malformed_workbook_template", "an unclosed brace is not a format string at all", True, _naming(workbook="{profile}_{period_label.xlsx"), semantic=True, findings=1),
    Case("malformed_worksheet_template", "the same, where the {source} rule also has to read it", True, _naming(worksheet="{source} {period_label"), semantic=True, findings=1),
    Case(
        "duplicate_profile_name",
        "two profiles of one name render one set of filenames",
        True,
        _mutate(profiles=[copy.deepcopy(BASE["profiles"][0]), {**copy.deepcopy(BASE["profiles"][0]), "output_subdirectory": "other"}]),
        semantic=True,
        findings=1,
    ),
    Case(
        "two_profiles_one_directory",
        "a subdirectory is owned exclusively, and a trailing separator is not a second directory",
        True,
        _mutate(profiles=[copy.deepcopy(BASE["profiles"][0]), {**copy.deepcopy(BASE["profiles"][0]), "name": "monthly", "output_subdirectory": "annual_review/"}]),
        semantic=True,
        findings=1,
    ),
]
"""Documents the schema accepts by design and the semantic validator rejects."""

ALL_CASES: list[Case] = [*VALID, *INVALID, *SEMANTIC, *DIALECT]
"""Every case, for the agreement check and for export."""

__all__ = ["ALL_CASES", "BASE", "DIALECT", "INVALID", "SEMANTIC", "VALID", "Case", "as_records", "render_artifact"]


def as_records() -> list[dict[str, Any]]:
    """Return every case as a plain JSON-serialisable record.

    The form the exported artifact takes, and the form a validator written in another language
    can consume: no Python types, no dataclasses, one object per case.

    Returns:
        One record per case, in corpus order.
    """
    return [
        {
            "id": case.identifier,
            "reason": case.reason,
            "structurally_valid": case.structurally_valid,
            "semantic_only": case.semantic,
            "expected_findings": case.findings,
            "dialect_divergence": case.dialect_divergence,
            "document": case.document,
        }
        for case in ALL_CASES
    ]


ARTIFACT_HEADER: str = "Generated by tools/build_config_corpus.py. Do not edit by hand."
"""Stamped into the exported JSON so nobody edits the copy instead of the source."""


def render_artifact() -> str:
    """Return the exported artifact's exact text, newline-terminated.

    Lives here rather than in the tool so the test that guards the committed file can compare
    against it without importing from ``tools/``, which is not a package on a test's import path.

    Returns:
        Pretty-printed JSON, stable across runs so a diff shows only real changes.
    """
    return json.dumps({"$comment": ARTIFACT_HEADER, "cases": as_records()}, indent=2, ensure_ascii=False, sort_keys=False) + "\n"
